# Generated by Django 6.0 on 2025-12-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
