# Generated by Django 6.0 on 2025-12-30 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'Parties'},
        ),
        migrations.RemoveField(
            model_name='party',
            name='Category_level',
        ),
        migrations.RemoveField(
            model_name='party',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='party',
            name='user',
        ),
        migrations.AddField(
            model_name='party',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='party',
            name='is_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='Category_type',
            field=models.CharField(choices=[('Customer', 'Individual'), ('Supplier', 'Company')], max_length=20),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('open_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit_limmit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('preferred_payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI')], max_length=20, null=True)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('referred_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='api.party')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Supplier', to='api.party')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('open_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit_limmit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_infos', to='api.supplier')),
            ],
        ),
    ]
