# Generated by Django 6.0 on 2026-01-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customer_customer_code_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='updated_at',
        ),
    ]
